### ISSUE TITLE
Unable to find the target class

### ISSUE THREAD

**Issue by khaeghar** [albertogoffi/toradocu#154]
In the refactor branch, at InequalitiesSupportTest, Toradocu throws an error:

[main] ERROR org.toradocu.Toradocu - Unable to find the target class: example.VariablesComparison
Possible reasons for the error are:
1. The qualified name of the target class is wrong: example.VariablesComparison
2. The path to the source code of your system is wrong: src/test/resources
3. The path to the binaries of your system is wrong: [file:/home/sergio/Repositories/toradocu-d/src/test/resources/]
Please, check the correctness of the command line arguments.
If the error persists, report the issue at https://github.com/albertogoffi/toradocu/issues

Both .java and .class are in the same folder, and they exist (Obviously).

To reproduce the error, just execute the test.

Can anyone relate about this fail or it is my system the only one that fails?

**Comment by albertogoffi** [comment]
I fixed the problem. Reason was the incorrect Javadoc documentation used in the test class `VariablesComparison.java`. You can see what I changed here: 233889dc0a3c546b8be9a15c066ae92559a09b40.

Note that the test case continues to fail. However, the reason is different.
I'll close this issue since the specific problem is now fixed.
