### ISSUE TITLE
Odd preprocessing of @param tags

### ISSUE THREAD

**Issue by albertogoffi** [albertogoffi/toradocu#207]
It seems that `@param` comments are preprocessed incorrectly.
For example the comment
`the map to decorate, must not be null`
is processed as
`the map to decorate .map must not be null.`

The class that performs this preprocessing is `org.toradocu.translator.preprocess.ImplicitParamSubjectPatterns`.

**Comment by ariannab** [comment]
The problem was in the involved old goal files, which were generated when pram preprocessing was slightly wrong. During tests, the output was showing the expected comment and not the one processed by Toradocu. 
I corrected such goal files. Also, now tests output the actual comment and not the one in the goal files. Preprocessing has been slightly refactored.
