### ISSUE TITLE
Wrong translation of comment “if <object> is null or this”

### ISSUE THREAD

**Issue by ariannab** [albertogoffi/toradocu#43]
Toradocu currently cannot translate properly the keyword `this` -  i.e. the Java reference to the current object.

To see an example of this behaviour, take a look at the project “FreeCol”: https://github.com/fenyo1/FreeCol.git

In the class` net.sf.freecol.common.model.Player` the method `setStance` takes a `Player` object as first
argument and must throw an exception “if player is null or this”. Toradocu correctly identifies the player as the subject and produces the condition `args[0]==null` , but the complete version should be `args[0]==null || args[0]==this`.

To reproduce this example, you can execute the following commands:

- FreeCol is an **ant** project, so you can build it by executing the command `ant` from the root folder, where `build.xml` is located. This will create the `FreeCol.jar`
(To run the command, ant must be installed in your system; ant is also integrated in the Eclipse IDE, if you prefer)
 
- Now that `FreeCol.jar` has been created you can compile the test suite:
 ```
 javac -cp FreeCol.jar:test/lib/junit.jar:src:test/src test/src/net/sf/freecol/common/model/PlayerTest.java
 ```
- And then, run it; you should get `OK (5 tests)`:
```
 java -cp test/lib/junit.jar:test/src:src:FreeCol.jar org.junit.runner.JUnitCore net.sf.freecol.common.model.PlayerTest
 ```
- In the end, run Toradocu (specify correctly the path to your  own .jar):
 ```
 java -jar toradocu-1.0-all.jar \
 --target-class net.sf.freecol.common.model.Player \
--test-class net.sf.freecol.common.model.PlayerTest \
 --source-dir src \
 --class-dir build \
 --aspects-output-dir aspects
 ```
 You can see the relevant part of the output also in the PDF file attached: [output_setStance.pdf](https://github.com/albertogoffi/toradocu/files/587129/output_setStance.pdf)

**Comment:** "if player is null or this"
**Expected Output:** `(args[0]==null || args[0]==this)`
**Actual Output:** `args[0]==null`

**Comment by albertogoffi** [comment]
The problem main issue is in `org.toradocu.translator.SentenceParser`.

**Comment by albertogoffi** [comment]
I investigated better the problem. The comment `player is null or this.` is parsed as
```
-> null/NN (root)
  -> player/NN (nsubj)
  -> is/VBZ (cop)
  -> or/CC (cc)
  -> this/DT (conj:or)
  -> ./. (punct)
```
while we'd expect the following tree (or anyway a tree with two `nsubj` relations):
```
-> null/JJ (root)
  -> player/NN (nsubj)
  -> is/VBZ (cop)
  -> or/CC (cc)
  -> this/JJ (conj:or)
    -> player/NN (nsubj)
```
The problem is due to the wrong POS tagging of the word `this` by the Stanford parser: `this` is classified as determiner (DT). Instead it should be a noun (NN) in this case (even though the parse tree is correct when `this` is classified as an adjective.)

A viable solution is to replace `this` with a placeholder to force the Stanford parser to correctly POS tag `this` and then generate a correct parse tree. Another solution could be pre-tag the word `this` with the correct POS tag.
