### ISSUE TITLE
"but" means "&&" not "||"

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#61]
For the `@param` in the following class
```java
package pkg;

public class Counter {
  /**
  * @param count  the count of all things wonderful, must be positive but less than 10
  */
  void wonderfulCount(int count) {}
}
```
The condition should be `count >0 && count < 10`, but Toradocu is generating `count > 0 || count < 10`.

Are there examples where the correct interpretation of "but" is not a conjunction?

**Comment by albertogoffi** [comment]
Toradocu uses `||` as the default operator to connect conditions.
`&&` is used in specific situations and we can indeed handle `but` to be treated as `and`.
We need to check the result of this change on the regression test suite, since I have no example in mind where the but should not be an and conjunction.
