### ISSUE TITLE
Randoop integration: need Class<>.getName() formatted string 

### ISSUE THREAD

**Issue by bjkeller** [albertogoffi/toradocu#86]
In order for Randoop to be able to use reflection to recreate types (especially member types), they need to be given in the format expected by `Class.forName()`, which is produced by `Class<>.getName()`.

For instance, Running Toradocu over JGraphT (https://github.com/randoop/jgrapht/tree/master/jgrapht-core) 
generates a JSON file with the member type `org.jgrapht.experimental.dag.DirectedAcyclicGraph.Visited` given in that format where the `Class.forName()` format would be `org.jgrapht.experimental.dag.DirectedAcyclicGraph$Visited`

**Comment by albertogoffi** [comment]
Can you please clarify the impact of this?

To use the reflection string format I think we need to change Toradocu quite a bit.
This is because the Javadoc extractor works on source code with Javadoc API and not with reflection API. We should consider to use reflection API everywhere, and collect additional information with Javadoc API where needed.

**Comment by bjkeller** [comment]
I need to verify this is actually the problem, but won't be able to until feb 28. 

I am changing Randoop to skip methods/conditions for which there is an error. 

For the long run, we will probably change how Randoop receives condition information so that it doesn't have to know Toradocu internal rules. 

--
Ben Keller 
bjkeller@vt.edu

**Comment by albertogoffi** [comment]
OK, just let me know the input format for Randoop so that we can change Toradocu accordingly.

**Comment by albertogoffi** [comment]
I
