### ISSUE TITLE
Wrong proposition (subject) extraction from "if any of the specified vertices is null"

### ISSUE THREAD

**Issue by ariannab** [albertogoffi/toradocu#90]
Currently, a comment (`@throws`) like `"if any of the specified vertices is null" `produces the following tree:
```
-> null/JJ (root)
  -> any/DT (nsubj)
    -> vertices/NNS (nmod:of)
      -> of/IN (case)
      -> the/DT (det)
      -> specified/VBN (amod)
  -> is/VBZ (cop)
  -> ./. (punct)
```
This example is taken from `org.jgrapht.experimental.dag.DirectedAcyclicGraph` .

As a result, with default distance threshold of `2`, no subject match is found (thus, empty condition). Instead, with distance `3`, the method `wait()` is matched as subject - but obviously it is not correct.

More acceptable subject in that comment could be: "any of the specified vertices", "specified vertices", or just "vertices". The expected condition should be: ` (args[0]==null || args[1]==null)`

**Comment by albertogoffi** [comment]
From the comment `if any of the specified vertices is null` Toradocu extracts the proposition `("any", "is null")`. Since the subject is in a sense incomplete, the match of the subject fails.

Notice that the proposition extraction works fine for the comment `"any specified vertex is null"` where the extracted proposition is `("any specified vertex", "is null")`.

**Comment by mernst** [comment]
In the sentence "any of the specified vertices is null", "any" is a noun and is the subject.  So I think the Stanford parser is correct, and this issue should not be about a claim that the extracted subject is wrong.

The referent of "any" is clear from context to a person.  Our goal is to make Toradocu connect it to the right code elements.  Maybe that is what this issue is about.  We might want to post-process, or create a different sentence to send to the parser, or do other things.

Having "any" as the subject is useful even to Toradocu because it indicates quantification.

**Comment by albertogoffi** [comment]
I agree, in fact I changed the title to make clear that the extraction of the subject during the proposition extraction phase is wrong, not the graph produce by the Stanford Parser.

We need to modify the simplistic algorithm we use to traverse the graph and collect the words composing the subject. I'm going to have a look at this.

**Comment by albertogoffi** [comment]
Checked-in a possible solution in branch [issue90](/albertogoffi/toradocu/tree/issue90).

**Comment by ariannab** [comment]
A similar example can be found in `org.apache.commons.collections4.CollectionUtils` .

**Comment:** "if any of the parameters is null."

**Tree:**
```
-> null/JJ (root)
  -> any/DT (nsubj)
    -> parameters/NNS (nmod:of)
      -> of/IN (case)
      -> the/DT (det)
  -> is/VBZ (cop)
  -> ./. (punct)
```

**Comment by albertogoffi** [comment]
As a note, the implementation in branch [issue90](/albertogoffi/toradocu/tree/issue90) provides the correct translation for the two examples reported so far in this discussion.
